# Generated by Django 5.2.17 on 2026-10-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('paquete', models.CharField(max_length=150)),
                ('url', models.URLField(help_text='URL del APK base (https)')),
                ('urls_splits', models.TextField(blank=True, help_text='URLs de los splits (split_config.*), una por línea. Vacío si es un solo APK.')),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=80, unique=True)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('android', models.CharField(blank=True, max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('bateria', models.IntegerField(blank=True, null=True)),
                ('kiosco_activo', models.BooleanField(null=True)),
                ('version_aplicada', models.PositiveIntegerField(blank=True, null=True)),
                ('visto', models.DateTimeField(blank=True, null=True)),
                ('inscrito', models.DateTimeField(auto_now_add=True)),
                ('consumo_total_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('consumo_por_app', models.JSONField(blank=True, default=dict)),
                ('tope_superado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['alias', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('clave', models.SlugField(max_length=60, unique=True)),
                ('kiosco', models.BooleanField(default=False)),
                ('apps', models.JSONField(blank=True, default=list)),
                ('restricciones', models.JSONField(blank=True, default=dict)),
                ('tope_total_mb', models.PositiveIntegerField(default=0, help_text='Tope mensual total del equipo en MB (0 = sin tope)')),
                ('version', models.PositiveIntegerField(default=1)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bloquear', 'Bloquear pantalla'), ('reiniciar', 'Reiniciar equipo'), ('instalar', 'Instalar aplicación'), ('desinstalar', 'Desinstalar aplicación'), ('sincronizar', 'Forzar sincronización')], max_length=20)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado al equipo'), ('ok', 'Completado'), ('error', 'Error')], default='pendiente', max_length=15)),
                ('resultado', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('entregado', models.DateTimeField(blank=True, null=True)),
                ('completado', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='app.dispositivo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='politica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.politica'),
        ),
    ]
