# Generated by Django 5.2.17 on 2026-10-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_revertir_a_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacion',
            name='urls_splits',
            field=models.TextField(blank=True, help_text='URLs de los splits (split_config.*), una por línea. Vacío si es un solo APK.'),
        ),
    ]
